AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  recommendation-service

  Sample SAM Template for recommendation-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  RecommendCandidatesToRecruiterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  RecommendCandidatesToRecruiterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: recommendCandidatesToRecruiter/
      Handler: app.recommend_candidates_to_recruiter
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        RecommendCandidatesToRecruiterApiEvent:
          Type: Api
          Properties:
            Path: /recommendCandidatesToRecruiter
            Method: POST

  RecommendJobsToCandidateApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  RecommendJobsToCandidateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: recommendJobsToCandidate/
      Handler: app.recommend_jobs_to_candidate
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        RecommendJobsToCandidateApiEvent:
          Type: Api
          Properties:
            Path: /recommendJobsToCandidate
            Method: POST

  JobDbDevApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  JobDbDevFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jobDbDev/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        JobDbDevApiEvent:
          Type: Api
          Properties:
            Path: /jobDbDev
            Method: GET

  CandiDbDevApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  CandiDbDevFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: candiDbDev/
      Handler: app.lambda_handler
      Runtime: python3.9 
      Architectures:
        - x86_64
      Events:
        CandiDbDevApiEvent:
          Type: Api
          Properties:
            Path: /candiDbDev
            Method: GET



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

  RecommendCandidatesToRecruiterApiUrl:
    Description: URL of the Recommend Candidates to Recruiter API
    Value:
      Fn::Sub: "https://${RecommendCandidatesToRecruiterApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/recommendCandidatesToRecruiter"
  RecommendCandidatesToRecruiterFunctionArn:
    Description: ARN of the Recommend Candidates to Recruiter Lambda function
    Value:
      Fn::GetAtt:
        - RecommendCandidatesToRecruiterFunction
        - Arn

  RecommendJobsToCandidateApiUrl:
    Description: URL of the Recommend Jobs to Candidate API
    Value:
      Fn::Sub: "https://${RecommendJobsToCandidateApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/recommendJobsToCandidate"
  RecommendJobsToCandidateFunctionArn:
    Description: ARN of the Recommend Jobs to Candidate Lambda function
    Value:
      Fn::GetAtt:
        - RecommendJobsToCandidateFunction
        - Arn

  JobDbDevApi:
    Description: URL of the Job database API to get list of jobs or a job
    Value:
      Fn::Sub: "https://${JobDbDevApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/jobDbDev"
  JobDbDevFunctionArn:
    Description: ARN of the Job database API Lambda function
    Value:
      Fn::GetAtt:
        - JobDbDevFunction
        - Arn

  CandiDbDevApi:
    Description: URL of the Job database API to get list of jobs or a job
    Value:
      Fn::Sub: "https://${CandiDbDevApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/candiDbDev"
  CandiDbDevFunctionArn:
    Description: ARN of the Job database API Lambda function
    Value:
      Fn::GetAtt:
        - JobDbDevFunction
        - Arn

