AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  recommendation-service

  Sample SAM Template for recommendation-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 128

Resources:
  RecommendCandidatesToRecruiterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: recommendCandidatesToRecruiter/
      Handler: app.recommend_candidates_to_recruiter
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        RecommendCandidatesToRecruiterApiEvent:
          Type: Api
          Properties:
            Path: /recommendCandidatesToRecruiter
            Method: POST

Outputs:
  RecommendCandidatesToRecruiterApiUrl:
    Description: "URL of the Recommend Candidates to Recruiter API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/recommendCandidatesToRecruiter/"
  RecommendCandidatesToRecruiterFunction:
    Description: "ARN of the Recommend Candidates to Recruiter Lambda function"
    Value: !GetAtt RecommendCandidatesToRecruiterFunction.Arn
  RecommendCandidatesToRecruiterFunctionIamRole:
    Description: "Implicit IAM Role created for RecommendCandidatesToRecruiter function"
    Value: !GetAtt RecommendCandidatesToRecruiterFunctionRole.Arn

