AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  recommendation-service

  Sample SAM Template for recommendation-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  RecommendCandidatesToRecruiterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: recommendCandidatesToRecruiter/
      Handler: app.recommend_candidates_to_recruiter
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 30
      Events:
        RecommendCandidatesToRecruiterApiEvent:
          Type: Api
          Properties:
            Path: /recommendCandidatesToRecruiter
            Method: GET

  RecommendJobsToCandidateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: recommendJobsToCandidate/
      Handler: app.recommend_jobs_to_candidate
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 30
      Events:
        RecommendJobsToCandidateApiEvent:
          Type: Api
          Properties:
            Path: /recommendJobsToCandidate
            Method: GET


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  RecommendCandidatesToRecruiterApiUrl:
    Description: "URL of the Recommend Candidates to Recruiter API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/recommendCandidatesToRecruiter/"
  RecommendCandidatesToRecruiterFunction:
    Description: "ARN of the Recommend Candidates to Recruiter Lambda function"
    Value: !GetAtt RecommendCandidatesToRecruiterFunction.Arn
  RecommendCandidatesToRecruiterFunctionIamRole:
    Description: "Implicit IAM Role created for RecommendCandidatesToRecruiter function"
    Value: !GetAtt RecommendCandidatesToRecruiterFunctionRole.Arn

  RecommendJobsToCandidateFunctionApiUrl:
    Description: "URL of the Recommend Jobs to Candidate API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/recommendJobsToCandidate/"
  RecommendJobsToCandidateFunction:
    Description: "ARN of the Recommend Jobs to Candidate Lambda function"
    Value: !GetAtt RecommendJobsToCandidateFunction.Arn
  RecommendJobsToCandidateFunctionIamRole:
    Description: "Implicit IAM Role created for RecommendJobsToCandidateFunction function"
    Value: !GetAtt RecommendJobsToCandidateFunctionRole.Arn

